@echo off
REM Auto-generated by Grok to build fresh AAB v0.1.9 after placing google-services.json from user indicated path.
REM Does web prep + cap sync + gradle clean bundleRelease (no publish, since track needs seed).

set "JAVA_HOME=C:\Program Files\Microsoft\jdk-21.0.11.10-hotspot"
set "ANDROID_HOME=C:\Android"
set "PATH=%JAVA_HOME%\bin;%ANDROID_HOME%\platform-tools;%ANDROID_HOME%\cmdline-tools\latest\bin;%PATH%"

echo ==========================================
echo EntrenaMatch - BUILD AAB v0.1.9 (json placed from indicated dir)
echo JAVA_HOME=%JAVA_HOME%
echo ANDROID_HOME=%ANDROID_HOME%
echo ==========================================

if not exist "android\app\google-services.json" (
  echo [ERROR] google-services.json missing - abort
  exit /b 1
)

echo.
echo Step 1: Full web build + Capacitor sync (CAPACITOR=1)
set CAPACITOR=1
call npm run android:build
if errorlevel 1 (
  echo [ERROR] android:build failed
  exit /b 1
)

echo.
echo Step 2: gradle clean bundleRelease (will run google-services check with our strict matcher)
cd /d android
call gradlew clean bundleRelease --stacktrace 2>&1 | findstr /C:"google-services" /C:"CONTAINS MATCHING" /C:"NO MATCHING CLIENT" /C:"BUILD SUCCESSFUL" /C:"BUILD FAILED" /C:"app-release.aab" /C:"> Task"
if errorlevel 1 (
  echo [WARN] gradle may have had issues, check full log
)

cd /d ..

echo.
echo Checking output AAB...
if exist "android\app\build\outputs\bundle\release\app-release.aab" (
  dir "android\app\build\outputs\bundle\release\app-release.aab"
  echo AAB ready for copy.
) else (
  echo [ERROR] No AAB produced.
)

echo.
echo Done. Now copy the AAB to root with versioned name.
echo ==========================================