import { describe, expect, it } from 'vitest'
import {
  buildFeedDisplayItems,
  isAutoGeneratedFeedPost,
  isAutoLiveFeedPost,
  pickLivePostText,
  userHasRecentAutoLivePost,
} from './feedPostMeta'

const base = (overrides: Record<string, unknown> = {}) => ({
  id: 'p1',
  ownerId: 'u1',
  timestamp: Date.now(),
  text: 'Hola comunidad',
  ...overrides,
})

describe('feedPostMeta', () => {
  it('detects auto live posts', () => {
    expect(
      isAutoLiveFeedPost(
        base({ text: '¡Entrenando ahora en el Mapa LIVE! ¿Quién se une? 🏋️' })
      )
    ).toBe(true)
    expect(isAutoLiveFeedPost(base({ text: 'Mi mejor set de sentadillas hoy', photo: 'x' }))).toBe(
      false
    )
  })

  it('detects auto generated but not manual workout posts', () => {
    expect(isAutoGeneratedFeedPost(base({ postType: 'workout' }))).toBe(false)
    expect(
      isAutoGeneratedFeedPost(base({ text: 'En chat con mi socio de EntrenaSync: ¿Entrenamos?' }))
    ).toBe(true)
  })

  it('groups three consecutive auto posts', () => {
    const posts = [
      base({ id: 'a', text: '¡Entrenando ahora en el Mapa LIVE!' }),
      base({ id: 'b', text: '¡Entrenando ahora en el GymPulse!' }),
      base({ id: 'c', text: 'En chat con mi socio de EntrenaSync: hola' }),
      base({ id: 'd', text: 'Foto del gym', photo: 'https://x.jpg' }),
    ]
    const items = buildFeedDisplayItems(posts)
    expect(items).toHaveLength(2)
    expect(items[0].kind).toBe('autoGroup')
    if (items[0].kind === 'autoGroup') expect(items[0].posts).toHaveLength(3)
    expect(items[1].kind).toBe('post')
  })

  it('skips duplicate live post when recent exists', () => {
    const now = Date.now()
    const store = {
      me: [base({ timestamp: now - 60_000, text: '¡Entrenando ahora en el Mapa LIVE!' })],
    }
    expect(userHasRecentAutoLivePost('me', store, 4 * 3_600_000, now)).toBe(true)
    expect(userHasRecentAutoLivePost('other', store, 4 * 3_600_000, now)).toBe(false)
  })

  it('rotates live post copy', () => {
    expect(pickLivePostText(0)).not.toBe(pickLivePostText(1))
  })
})
