import { getDistanceKm } from './index'
import { isUserLiveInSnapshot, type LiveUserLike } from './gymPulseLive'
import { isAutoGeneratedFeedPost, isEchoPost } from './feedPostMeta'

export interface FeedPostRow {
  id?: string
  ownerId: string
  timestamp: number
  text?: string
  pinned?: boolean
  isMine?: boolean
  postType?: string
  [key: string]: unknown
}

export interface FeedRankingContext {
  syncBonds: Record<string, { bondLevel?: number }>
  liveUsersActive: LiveUserLike[]
  userLocation?: { lat: number; lng: number } | null
  ownerCoords?: Record<string, { lat: number; lng: number }>
  now?: number
}

export interface FeedRankBadges {
  live: boolean
  near: boolean
  bond: boolean
  echo: boolean
}

const WEIGHTS = {
  bondBase: 400,
  bondPerLevel: 120,
  echo: 350,
  live: 280,
  pinned: 80,
  workout: 60,
  recencyMax: 200,
  proximityMax: 150,
  hasPhoto: 140,
  commentEach: 28,
  commentCap: 110,
  autoPost: 200,
} as const

const RECENCY_WINDOW_MS = 7 * 86_400_000
const NEAR_KM = 8

export { isEchoPost } from './feedPostMeta'

export function computeFeedPostScore(post: FeedPostRow, ctx: FeedRankingContext): number {
  const now = ctx.now ?? Date.now()
  let score = 0

  const bond = ctx.syncBonds[post.ownerId]
  if (bond) {
    score += WEIGHTS.bondBase + (bond.bondLevel || 1) * WEIGHTS.bondPerLevel
  }
  if (isEchoPost(post)) score += WEIGHTS.echo
  if (isUserLiveInSnapshot(post.ownerId, ctx.liveUsersActive, now)) score += WEIGHTS.live
  if (post.pinned) score += WEIGHTS.pinned
  if (post.postType === 'workout') score += WEIGHTS.workout
  if (post.photo) score += WEIGHTS.hasPhoto

  const comments = (post.comments as Array<unknown> | undefined) || []
  score += Math.min(comments.length * WEIGHTS.commentEach, WEIGHTS.commentCap)

  if (isAutoGeneratedFeedPost(post)) score -= WEIGHTS.autoPost

  const ts = post.timestamp || 0
  const ageMs = Math.max(0, now - ts)
  score += WEIGHTS.recencyMax * Math.max(0, 1 - ageMs / RECENCY_WINDOW_MS)

  if (ctx.userLocation && ctx.ownerCoords?.[post.ownerId]) {
    const { lat, lng } = ctx.ownerCoords[post.ownerId]
    const dist = getDistanceKm(ctx.userLocation.lat, ctx.userLocation.lng, lat, lng)
    if (dist <= NEAR_KM) {
      score += WEIGHTS.proximityMax * Math.max(0, 1 - dist / NEAR_KM)
    }
  }

  return score
}

export interface FeedDisplayBadge {
  label: string
  className: string
}

export interface PickFeedBadgesInput {
  isMine: boolean
  isReal: boolean
  isPinned: boolean
  isNew: boolean
  isSyncPost: boolean
  isEcho: boolean
  ownerTrainingNow: boolean
  rankBadges: FeedRankBadges | null
  maxBadges?: number
}

/** At most 2 badges per post — highest-signal first (live, cerca, highlight…). */
export function pickFeedDisplayBadges(input: PickFeedBadgesInput): FeedDisplayBadge[] {
  const max = input.maxBadges ?? 2
  const candidates: Array<{ priority: number } & FeedDisplayBadge> = []

  if (input.isPinned) {
    candidates.push({
      priority: 100,
      label: '📌 FIJADO',
      className: 'feed-author-badge bg-[#FF671F]/15 text-[#FF671F]',
    })
  }
  if (input.ownerTrainingNow) {
    candidates.push({
      priority: 90,
      label: '🟢 LIVE AHORA',
      className: 'feed-author-badge bg-[#22c55e] text-black',
    })
  } else if (input.rankBadges?.live) {
    candidates.push({
      priority: 85,
      label: '🟢 LIVE',
      className: 'feed-author-badge bg-[#22c55e]/90 text-black',
    })
  }
  if (input.isEcho) {
    candidates.push({
      priority: 80,
      label: 'HIGHLIGHT',
      className: 'feed-author-badge bg-[#FFD700] text-black',
    })
  }
  if (input.isSyncPost) {
    candidates.push({
      priority: 75,
      label: 'SYNC',
      className: 'feed-author-badge bg-[#22c55e] text-black',
    })
  }
  if (input.rankBadges?.near) {
    candidates.push({
      priority: 70,
      label: '📍 CERCA',
      className: 'feed-author-badge bg-[#3b82f6] text-white',
    })
  }
  if (input.rankBadges?.bond) {
    candidates.push({
      priority: 65,
      label: 'RED',
      className: 'feed-author-badge bg-[#FFD700]/20 text-[#FFD700]',
    })
  }
  if (input.isNew) {
    candidates.push({
      priority: 50,
      label: 'NUEVO',
      className: 'feed-author-badge bg-[#22c55e] text-black',
    })
  }
  if (input.isMine) {
    candidates.push({
      priority: 40,
      label: 'TÚ',
      className: 'feed-author-badge bg-[#FFD700] text-black',
    })
  }
  if (input.isReal) {
    candidates.push({
      priority: 30,
      label: 'REAL',
      className: 'feed-author-badge bg-[#FF671F] text-black',
    })
  }

  return candidates
    .sort((a, b) => b.priority - a.priority)
    .slice(0, max)
    .map(({ label, className }) => ({ label, className }))
}

/** No more than `maxConsecutive` posts in a row from the same author. */
export function limitConsecutiveSameAuthor<T extends FeedPostRow>(
  posts: T[],
  maxConsecutive = 2
): T[] {
  if (posts.length <= maxConsecutive) return [...posts]

  const result: T[] = []
  const pool = [...posts]

  while (pool.length > 0) {
    let pickIdx = 0
    if (result.length >= maxConsecutive) {
      const tail = result.slice(-maxConsecutive)
      const blockedOwner = tail[0].ownerId
      if (tail.every((p) => p.ownerId === blockedOwner)) {
        const altIdx = pool.findIndex((p) => p.ownerId !== blockedOwner)
        if (altIdx >= 0) pickIdx = altIdx
      }
    }
    result.push(pool.splice(pickIdx, 1)[0])
  }

  return result
}

export function getFeedRankBadges(post: FeedPostRow, ctx: FeedRankingContext): FeedRankBadges {
  const now = ctx.now ?? Date.now()
  let near = false
  if (ctx.userLocation && ctx.ownerCoords?.[post.ownerId]) {
    const { lat, lng } = ctx.ownerCoords[post.ownerId]
    near = getDistanceKm(ctx.userLocation.lat, ctx.userLocation.lng, lat, lng) <= NEAR_KM
  }
  return {
    live: isUserLiveInSnapshot(post.ownerId, ctx.liveUsersActive, now),
    near,
    bond: !!ctx.syncBonds[post.ownerId],
    echo: isEchoPost(post),
  }
}

export function sortFeedPosts<T extends FeedPostRow>(posts: T[], ctx: FeedRankingContext): T[] {
  return [...posts].sort((a, b) => {
    const sa = computeFeedPostScore(a, ctx)
    const sb = computeFeedPostScore(b, ctx)
    if (sb !== sa) return sb - sa
    return (b.timestamp || 0) - (a.timestamp || 0)
  })
}

export interface FeedComputeParams {
  profilePosts: Record<string, FeedPostRow[] | undefined>
  effectiveUserId: string
  syncBonds: Record<string, { bondLevel?: number }>
  liveUsersActive: LiveUserLike[]
  userLocation?: { lat: number; lng: number } | null
  realProfiles: Array<{ id: string; lat?: number; lng?: number; name?: string }>
  currentUser?: { name?: string; lat?: number; lng?: number } | null
  feedShowPinnedOnly: boolean
  feedOnlyReal: boolean
  feedOnlyLive: boolean
  feedSearch: string
  feedDisplayLimit: number
  isSeedProfileId: (id: string) => boolean
  now?: number
}

export function buildOwnerCoordsMap(
  realProfiles: Array<{ id: string; lat?: number; lng?: number }>,
  currentUser?: { id?: string; lat?: number; lng?: number } | null,
  effectiveUserId?: string
): Record<string, { lat: number; lng: number }> {
  const map: Record<string, { lat: number; lng: number }> = {}
  for (const p of realProfiles) {
    if (Number.isFinite(p.lat) && Number.isFinite(p.lng)) {
      map[p.id] = { lat: p.lat!, lng: p.lng! }
    }
  }
  if (
    currentUser &&
    effectiveUserId &&
    Number.isFinite(currentUser.lat) &&
    Number.isFinite(currentUser.lng)
  ) {
    map[effectiveUserId] = { lat: currentUser.lat!, lng: currentUser.lng! }
  }
  return map
}

/** Fase 141/221 — composite feed ranking (bond + live + recency + proximity). */
export function computeGlobalFeed(params: FeedComputeParams) {
  const {
    profilePosts,
    effectiveUserId,
    syncBonds,
    liveUsersActive,
    userLocation,
    realProfiles,
    currentUser,
    feedShowPinnedOnly,
    feedOnlyReal,
    feedOnlyLive,
    feedSearch,
    feedDisplayLimit,
    isSeedProfileId,
    now = Date.now(),
  } = params

  const allCommunityPosts = Object.entries(profilePosts)
    .filter(([uid]) => uid !== effectiveUserId)
    .flatMap(([uid, posts]) => (posts || []).map((p) => ({ ...p, ownerId: uid })))

  const myPostsRaw = (profilePosts[effectiveUserId] || []).map((p) => ({
    ...p,
    ownerId: effectiveUserId,
    isMine: true,
  }))

  const rankingCtx: FeedRankingContext = {
    syncBonds,
    liveUsersActive,
    userLocation,
    ownerCoords: buildOwnerCoordsMap(realProfiles, currentUser, effectiveUserId),
    now,
  }

  let feedPosts = sortFeedPosts([...allCommunityPosts, ...myPostsRaw], rankingCtx)

  const hasActiveFilter =
    feedShowPinnedOnly || feedOnlyReal || feedOnlyLive || !!feedSearch.trim()

  if (feedShowPinnedOnly) feedPosts = feedPosts.filter((p) => p.pinned)
  if (feedOnlyReal) {
    feedPosts = feedPosts.filter((p) => p.isMine || !isSeedProfileId(p.ownerId))
  }
  if (feedOnlyLive) {
    feedPosts = feedPosts.filter(
      (p) => !p.isMine && isUserLiveInSnapshot(p.ownerId, liveUsersActive, now)
    )
  }
  if (feedSearch.trim()) {
    const q = feedSearch.toLowerCase().trim()
    feedPosts = feedPosts.filter((p) => {
      const ownerName = p.isMine
        ? currentUser?.name || ''
        : (realProfiles.find((r) => r.id === p.ownerId) || { name: '' }).name
      return (
        (p.text || '').toLowerCase().includes(q) ||
        (ownerName || '').toLowerCase().includes(q)
      )
    })
  }

  feedPosts = limitConsecutiveSameAuthor(feedPosts).slice(0, feedDisplayLimit)

  return {
    feedPosts,
    allCommunityPosts,
    echoesSource: [...allCommunityPosts, ...myPostsRaw],
    hasActiveFilter,
    rankingCtx,
  }
}
