import type { FeedPostRow } from './feedRanking' // type-only — no runtime cycle with feedRanking

export function isEchoPost(post: FeedPostRow): boolean {
  const text = post.text || ''
  return (
    text.includes('HIGHLIGHT DE ENTRENASYNC') ||
    text.includes('Destacado de Sesión Sync') ||
    text.includes('Vi un EntrenaSync') ||
    text.includes('HIGHLIGHT') ||
    text.includes('Fui testigo')
  )
}

const AUTO_TEXT_MARKERS = [
  'entrenando ahora',
  'mapa live',
  'gympulse',
  'entrenasync completado',
  'en chat con mi socio',
  'completé mi reto diario',
  'reto diario completado',
  'racha ',
  'nivel ',
  'retención',
  'sincronizado',
  'momento de alta energía',
  'momento arena',
  '¿quién se une al pulso',
] as const

const LIVE_TEXT_MARKERS = ['entrenando ahora', 'mapa live', 'gympulse', '¿quién se une'] as const

export type AutoPostKind = 'live' | 'sync' | 'chat' | 'dailyPulse' | 'echo' | 'other'

export type FeedDisplayItem =
  | { kind: 'post'; post: FeedPostRow }
  | { kind: 'autoGroup'; id: string; posts: FeedPostRow[] }

export function isAutoLiveFeedPost(post: FeedPostRow): boolean {
  if (post.photo || post.pinned) return false
  if (post.postType === 'dailyPulse') {
    const text = (post.text || '').toLowerCase()
    return LIVE_TEXT_MARKERS.some((m) => text.includes(m))
  }
  const text = (post.text || '').toLowerCase()
  return LIVE_TEXT_MARKERS.some((m) => text.includes(m))
}

export function isAutoGeneratedFeedPost(post: FeedPostRow): boolean {
  if (post.photo || post.pinned) return false
  if (post.postType === 'dailyPulse' || post.postType === 'sync') return true
  if (isEchoPost(post)) return false
  if (post.postType === 'workout' || post.postType === 'nutrition' || post.postType === 'video') {
    return false
  }
  const text = (post.text || '').toLowerCase()
  return AUTO_TEXT_MARKERS.some((m) => text.includes(m))
}

export function getAutoPostKind(post: FeedPostRow): AutoPostKind {
  if (isEchoPost(post)) return 'echo'
  const text = (post.text || '').toLowerCase()
  if (post.postType === 'sync' || text.includes('entrenasync') || text.includes('sincronizado')) {
    return 'sync'
  }
  if (text.includes('en chat con mi socio')) return 'chat'
  if (isAutoLiveFeedPost(post)) return 'live'
  if (post.postType === 'dailyPulse') return 'dailyPulse'
  return 'other'
}

export function getAutoPostSummary(post: FeedPostRow, ownerName?: string): string {
  const who = (ownerName || 'Alguien').split(' ')[0]
  switch (getAutoPostKind(post)) {
    case 'live':
      return `${who} está entrenando en vivo`
    case 'sync':
      return `${who} compartió un EntrenaSync`
    case 'chat':
      return `${who} invitó a entrenar por chat`
    case 'dailyPulse':
      return `${who} completó un reto diario`
    case 'echo':
      return `${who} vio un EntrenaSync en el mapa`
    default:
      return (post.text || '').slice(0, 72)
  }
}

export function shouldGroupAsAuto(post: FeedPostRow): boolean {
  return isAutoGeneratedFeedPost(post) && !isEchoPost(post)
}

/** Group 3+ consecutive low-signal auto posts into one expandable card. */
export function buildFeedDisplayItems(posts: FeedPostRow[], minGroupSize = 3): FeedDisplayItem[] {
  const items: FeedDisplayItem[] = []
  let buffer: FeedPostRow[] = []

  const flush = () => {
    if (buffer.length >= minGroupSize) {
      items.push({
        kind: 'autoGroup',
        id: `ag-${buffer.map((p) => p.id || p.timestamp).join('-')}`,
        posts: [...buffer],
      })
    } else {
      buffer.forEach((p) => items.push({ kind: 'post', post: p }))
    }
    buffer = []
  }

  for (const post of posts) {
    if (shouldGroupAsAuto(post)) {
      buffer.push(post)
    } else {
      flush()
      items.push({ kind: 'post', post })
    }
  }
  flush()
  return items
}

export function pickLivePostText(seed = Date.now()): string {
  const variants = [
    '¡Entrenando ahora en el Mapa LIVE! ¿Quién se une?',
    'Sesión en curso — abrí el Mapa LIVE. ¿Te sumas?',
    'Racha activa: entrenando ahora cerca. ¿Quién me acompaña?',
  ]
  return variants[Math.abs(seed) % variants.length]
}

export function userHasRecentAutoLivePost(
  userId: string,
  postsByUser: Record<string, FeedPostRow[] | undefined>,
  windowMs = 4 * 3_600_000,
  now = Date.now()
): boolean {
  return (postsByUser[userId] || []).some(
    (p) => isAutoLiveFeedPost(p) && now - (p.timestamp || 0) < windowMs
  )
}
