/**
 * P0 one-shot setup: mapEditors in Firestore + .env.local dev password.
 * Usage: node scripts/setup-p0.mjs [--email=you@example.com]
 * Without --email: adds all Firebase Auth users (closed beta).
 */
import { readFileSync, writeFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { randomBytes } from 'crypto'
import { createRequire } from 'module'

const require = createRequire(import.meta.url)
const admin = require('../functions/node_modules/firebase-admin')

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const saPath = join(root, 'android', 'play-service-account.json')

function writeEnvLocal(password) {
  const envPath = join(root, '.env.local')
  writeFileSync(
    envPath,
    `# Auto-generated by scripts/setup-p0.mjs — do not commit\nVITE_DEV_MAP_PASSWORD=${password}\n`,
    'utf8'
  )
  console.log(`✓ .env.local written`)
}

async function initAdminApp() {
  const attempts = []

  if (existsSync(saPath)) {
    const sa = JSON.parse(readFileSync(saPath, 'utf8'))
    attempts.push({
      label: 'play-service-account.json',
      init: () =>
        admin.initializeApp({
          credential: admin.credential.cert(sa),
          projectId: 'entrenamatch',
        }),
    })
  }

  attempts.push({
    label: 'Application Default Credentials',
    init: () =>
      admin.initializeApp({
        credential: admin.credential.applicationDefault(),
        projectId: 'entrenamatch',
      }),
  })

  for (const attempt of attempts) {
    try {
      if (admin.apps.length) {
        await Promise.all(admin.apps.map((app) => app.delete()))
      }
      attempt.init()
      await admin.auth().listUsers(1)
      console.log(`Using ${attempt.label}`)
      return admin
    } catch (e) {
      console.warn(`${attempt.label} failed:`, e.message || e)
      if (admin.apps.length) {
        await Promise.all(admin.apps.map((app) => app.delete()))
      }
    }
  }

  throw new Error(
    'No credential with Firebase Admin (Auth + Firestore). Grant the Play service account "Firebase Admin SDK Administrator" in Google Cloud IAM, or run: gcloud auth application-default login'
  )
}

async function resolveUsers(auth) {
  const emailArg = process.argv.find((a) => a.startsWith('--email='))
  if (emailArg) {
    const email = emailArg.split('=')[1]
    const u = await auth.getUserByEmail(email)
    return [u]
  }

  const users = []
  let nextPageToken
  do {
    const result = await auth.listUsers(1000, nextPageToken)
    users.push(...result.users)
    nextPageToken = result.pageToken
  } while (nextPageToken)

  if (users.length === 0) {
    console.warn('No Firebase Auth users — create an account in the app, then re-run.')
  }
  return users
}

async function main() {
  const password = randomBytes(18).toString('base64url')
  writeEnvLocal(password)

  const app = await initAdminApp()
  const db = app.firestore()
  const auth = app.auth()

  const users = await resolveUsers(auth)
  for (const user of users) {
    await db.doc(`mapEditors/${user.uid}`).set(
      {
        role: 'map',
        email: user.email || null,
        addedBy: 'setup-p0.mjs',
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      },
      { merge: true }
    )
    console.log(`✓ mapEditors/${user.uid} (${user.email || 'no-email'})`)
  }

  console.log('\n--- Password editor mapa (también en .env.local) ---')
  console.log(password)
  console.log('--- Fin ---\n')
}

main().catch((e) => {
  console.error('setup-p0 failed:', e.message || e)
  process.exit(1)
})
